<?php

namespace ContainerWquer7Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HVtPB4zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hVtPB4z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hVtPB4z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.hVtPB4z.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator.hVtPB4z": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'id' => 'App\\Entity\\Utilisateur',
            'manager' => '?',
        ]);
    }
}
