<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYiBbudt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYiBbudt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYiBbudt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYiBbudt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYiBbudt\App_KernelDevDebugContainer([
    'container.build_hash' => 'YiBbudt',
    'container.build_id' => '255984f4',
    'container.build_time' => 1611314423,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYiBbudt');
