<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHlFSYnj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHlFSYnj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHlFSYnj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHlFSYnj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHlFSYnj\App_KernelDevDebugContainer([
    'container.build_hash' => 'HlFSYnj',
    'container.build_id' => '136e0c9d',
    'container.build_time' => 1612516497,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHlFSYnj');
