<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhAGIIG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhAGIIG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZhAGIIG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZhAGIIG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZhAGIIG\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZhAGIIG',
    'container.build_id' => '875aaf01',
    'container.build_time' => 1616150171,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhAGIIG');
